version: "3"
services:
  telinapp:
    image: petersantoso/telin-registration-app:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
